services:  
  postgresql:
    image: bitnami/postgresql:15.10.0-debian-12-r2
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRESQL_PORT_DEV:-5432}:5432"
    environment:
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME_DEV:-postgres}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD_DEV:-root}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE_DEV:-postgres}"
    volumes:
      - postgresql_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"${POSTGRESQL_USERNAME_DEV}\" -d \"${POSTGRESQL_DATABASE_DEV}\""]
      timeout: 20s
      retries: 3

  postgresql-test:
    image: bitnami/postgresql:15.10.0-debian-12-r2
    container_name: postgresql-test
    ports:
      - "${POSTGRESQL_PORT__TEST:-5433}:5432"
    environment:
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME_TEST:-postgres}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD_TEST:-root}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE_TEST:-postgres}"
      POSTGRESQL_POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD_TEST:-root}"
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: ""
    tmpfs:
      - /bitnami/postgresql:rw,size=512m,uid=1001,gid=1001
    command: >
      /opt/bitnami/scripts/postgresql/run.sh
      -c shared_buffers=64MB
      -c max_connections=20
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_buffers=1MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.0
      -c effective_cache_size=128MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"${POSTGRESQL_USERNAME_TEST}\" -d \"${POSTGRESQL_DATABASE_TEST}\""]
      interval: 2s
      timeout: 5s
      retries: 5
    profiles:
      - test

volumes:
  postgresql_data:
   